# Generated by Django 5.0.7 on 2026-04-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='customer_photo',
            field=models.ImageField(blank=True, null=True, upload_to='service_photos/%Y/%m/%d/'),
        ),
    ]
