# Generated by Django 5.0.7 on 2026-04-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_servicerequest_customer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicehistory',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Credit/Debit Card'), ('upi', 'UPI'), ('cash', 'Cash on Service')], max_length=20, null=True),
        ),
    ]
