# Generated by Django 6.0.3 on 2026-04-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_servicehistory_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='fuel_quantity',
            field=models.IntegerField(blank=True, help_text='Liters of fuel for fuel services', null=True),
        ),
    ]
