# Generated by Django 6.0.2 on 2026-04-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_servicerequest_fuel_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance in km for fuel delivery', max_digits=5, null=True),
        ),
    ]
