# Generated by Django 6.0.2 on 2026-05-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_distance_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='customer_photo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
